
project_id = "jegdbtznkwzpqntzzlvf"

[functions.generateLinkAPI]
verify_jwt = false

[functions.sendLinkedFormWebhook]
verify_jwt = false

[functions.auto-save-simulation]
verify_jwt = false

[functions.save-simulation]
verify_jwt = false

[functions.send-ycloud-message]
verify_jwt = false

[functions.generate-lead-pdf]
verify_jwt = false

[functions.cleanup-temp-pdfs]
verify_jwt = false

[functions.generate-ai-notes]
verify_jwt = false
