// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jegdbtznkwzpqntzzlvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplZ2RidHpua3d6cHFudHp6bHZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjExNzksImV4cCI6MjA2MzMzNzE3OX0.KS7wtHU2jRggJ06JKu_4YbVOvn8Bvz04wfE0qLpQPwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);